# Generated by Django 5.0.6 on 2024-06-21 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tutulo')),
                ('comment', models.CharField(max_length=500, verbose_name='Comentario')),
                ('img', models.ImageField(blank=True, null=True, upload_to='material/', verbose_name='Material grafico')),
                ('doc', models.FileField(blank=True, null=True, upload_to='material/', verbose_name='Material escrito')),
                ('videos', models.FileField(blank=True, null=True, upload_to='material/', verbose_name='Material de video')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('c', 'empresa'), ('p', 'profesor'), ('s', 'estudiante'), ('a', 'administrador')], default='s', max_length=1, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.FileField(upload_to='Announcement/', verbose_name='Detalle')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('detail', models.CharField(max_length=500, verbose_name='Detalle')),
                ('clases', models.IntegerField(verbose_name='Clases')),
                ('status', models.CharField(choices=[('i', 'inscripción'), ('d', 'desarrollo'), ('f', 'finalizado')], default='i', max_length=1, verbose_name='Estado')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.content', verbose_name='Contenido')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('present', models.BooleanField(blank=True, default=False, null=True, verbose_name='Presente')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL, verbose_name='Alumno')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_1', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 1')),
                ('mark_2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 2')),
                ('mark_3', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 3')),
                ('average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Promedio')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course', verbose_name='Curso')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'estudiantes'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Alumno regular')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course', verbose_name='Curso')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registration', to=settings.AUTH_USER_MODEL, verbose_name='Alumno')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150, verbose_name='Ciudad')),
                ('image', models.ImageField(default='defaultUser.png', upload_to='user/', verbose_name='Imagen')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefono')),
                ('description', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('cv', models.FileField(blank=True, null=True, upload_to='user/', verbose_name='CV')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('userType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usertype', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('detail', models.CharField(max_length=500, verbose_name='Detalle')),
                ('userType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usertype', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Membresia',
                'verbose_name_plural': 'Membresias',
            },
        ),
    ]
