# Generated by Django 5.0.6 on 2024-06-23 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='clases',
            new_name='classes',
        ),
    ]
